apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc-jobs
  namespace: jenkins
  labels:
    app: jenkins
    jenkins-jenkins-config: "true"
data:
  jobs.yaml: |
    jobs:
      - script: >
          pipelineJob('nginx-api-build') {
            description('Build and deploy nginx-api Node.js application (with nginx reverse proxy) to nginx-api-cluster')
            
            properties {
              githubProjectUrl('https://github.com/peterboddev/eks_jenkins_central_api_gw_app_ekses')
            }
            
            triggers {
              githubPush()
            }
            
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/peterboddev/eks_jenkins_central_api_gw_app_ekses.git')
                    }
                    branches('*/main')
                  }
                }
                scriptPath('jenkins-jobs/nginx-api-build/Jenkinsfile')
                lightweight(true)
              }
            }
          }
      - script: >
          pipelineJob('nginx-docker-build') {
            description('Build nginx demo Docker image')
            
            triggers {
              githubPush()
            }
            
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/peterboddev/eks_jenkins_central_api_gw_app_ekses.git')
                    }
                    branches('*/main')
                  }
                }
                scriptPath('jenkins-jobs/nginx-docker-build/Jenkinsfile')
                lightweight(true)
              }
            }
          }
