# CSIDriver object for EFS CSI Driver
# This resource defines the CSI driver and its capabilities
#
# Requirements: 6.8 - EKS cluster has EFS CSI Driver installed for dynamic volume provisioning
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: efs.csi.aws.com
  labels:
    app.kubernetes.io/name: aws-efs-csi-driver
spec:
  # EFS CSI Driver does not support volume attachment
  attachRequired: false
  # EFS CSI Driver supports persistent volumes
  podInfoOnMount: false
  # EFS CSI Driver supports volume expansion
  volumeLifecycleModes:
    - Persistent
